/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.tblBooks_SE140736;
import dto.Books_SE140736;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ManagementUI_SE140736 extends javax.swing.JFrame {

    tblBooks_SE140736 modelBook;

    final int SUCCESS = 1;
    boolean addNewBook = true;
    boolean deleteBook = true;

    public ManagementUI_SE140736() {
        initComponents();
        this.setSize(1100, 600);
        this.setLocationRelativeTo(null);

        modelBook = new tblBooks_SE140736();
        tblBook.setModel(modelBook.getModelBooks());

        loadPublishedYearIntoComboBox();

        cbxPublishedYear.setSelectedIndex(-1);
        cbxSortByName.setSelectedIndex(-1);
    }

    public void loadPublishedYearIntoComboBox() {
        for (int i = 1985; i < 2021; i++) {
            cbxPublishedYear.addItem(String.valueOf(i));
        }
    }

    public void loadSortByName() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Ascending");
        model.addElement("Descending");

        cbxPublishedYear.setModel(model);
        cbxPublishedYear.setSelectedIndex(-1);
    }

    void clearInformationBookOnTable() {
        txtBookID.setText("");
        txtBookName.setText("");
        txtBookName.setEnabled(true);
        txtAuthor.setText("");
        txtAuthor.setEnabled(true);
        txtPublisher.setText("");
        txtPublisher.setEnabled(true);
        cbxPublishedYear.setSelectedIndex(-1);
        cbxPublishedYear.setEnabled(true);
        chkForRent.setSelected(false);
        chkForRent.setEnabled(true);
        cbxSortByName.setSelectedIndex(-1);
    }

    private void clearAllBook() {
        txtBookID.setText("");
        txtBookName.setText("");
        txtBookName.setEnabled(false);
        txtAuthor.setText("");
        txtAuthor.setEnabled(false);
        txtPublisher.setText("");
        txtPublisher.setEnabled(false);
        cbxPublishedYear.setSelectedIndex(-1);
        cbxPublishedYear.setEnabled(false);
        chkForRent.setSelected(false);
        chkForRent.setEnabled(false);

        cbxSortByName.setSelectedIndex(-1);
        cbxSortByName.setEnabled(true);
        txtSearchByName.setText("");

    }

    private void clearMouseClickedBook() {
        txtBookName.setEnabled(true);
        txtAuthor.setEnabled(true);
        txtPublisher.setEnabled(true);
        cbxPublishedYear.setEnabled(true);
        chkForRent.setEnabled(true);

    }

    private void clearBookSort() {
        txtBookID.setText("");
        txtBookName.setText("");
        txtBookName.setEnabled(false);
        txtAuthor.setText("");
        txtAuthor.setEnabled(false);
        txtPublisher.setText("");
        txtPublisher.setEnabled(false);
        cbxPublishedYear.setSelectedIndex(-1);
        cbxPublishedYear.setEnabled(false);
        chkForRent.setSelected(false);
        chkForRent.setEnabled(false);

        cbxSortByName.setEnabled(true);
        txtSearchByName.setText("");
    }

    public void displayDetailBook(Books_SE140736 book) {
        txtBookID.setText(book.getBookID());
        txtBookName.setText(book.getBookName());
        txtAuthor.setText(book.getAuthor());
        txtPublisher.setText(book.getPublisher());
        cbxPublishedYear.setSelectedIndex(book.getPublishedYear() - 1985);
        if (book.isForRent() == true) {
            chkForRent.setSelected(true);
        } else {
            chkForRent.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbxSortByName = new javax.swing.JComboBox<>();
        txtSearchByName = new javax.swing.JTextField();
        btnGetAllBook = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        txtPublisher = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtBookName = new javax.swing.JTextField();
        btnFindID = new javax.swing.JButton();
        cbxPublishedYear = new javax.swing.JComboBox<>();
        chkForRent = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Book Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(392, 13, 222, 29);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main part:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBook);

        jLabel2.setText("Sort by name:");

        cbxSortByName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        cbxSortByName.setToolTipText("");
        cbxSortByName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSortByNameItemStateChanged(evt);
            }
        });
        cbxSortByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSortByNameActionPerformed(evt);
            }
        });

        btnGetAllBook.setText("Get all book");
        btnGetAllBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllBookActionPerformed(evt);
            }
        });

        btnSearch.setText("Search by name");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxSortByName, 0, 150, Short.MAX_VALUE)
                    .addComponent(txtSearchByName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetAllBook)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxSortByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btnGetAllBook)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 67, 552, 473);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detailed part:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel3.setText("Book ID:");

        jLabel4.setText("Boook name:");

        jLabel5.setText("Author:");

        jLabel6.setText("Publisher:");

        jLabel7.setText("Published year:");

        btnFindID.setText("Find by ID");
        btnFindID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindIDActionPerformed(evt);
            }
        });

        cbxPublishedYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021" }));

        chkForRent.setText("For rent");

        btnAdd.setText("Add new");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(71, 71, 71)
                        .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxPublishedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkForRent)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(81, 81, 81)
                        .addComponent(btnRemove)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindID))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxPublishedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkForRent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSave)
                    .addComponent(btnRemove))
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(570, 67, 505, 473);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked
        int selectedRow = tblBook.getSelectedRow();
        Books_SE140736 b = modelBook.getModelBooks().getList().get(selectedRow);
        txtBookID.setText(b.getBookID());
        txtBookName.setText(b.getBookName());
        txtAuthor.setText(b.getAuthor());
        txtPublisher.setText(b.getPublisher());
        cbxPublishedYear.setSelectedIndex(b.getPublishedYear() - 1985);
        chkForRent.setSelected(b.isForRent());
        cbxSortByName.setSelectedIndex(-1);
        addNewBook = false;
        deleteBook = true;
    }//GEN-LAST:event_tblBookMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        clearInformationBookOnTable();
        addNewBook = true;
        deleteBook = false;
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!modelBook.validData(txtBookID.getText().trim(), txtBookName.getText().trim(), txtAuthor.getText().trim(),
                txtPublisher.getText().trim())) {
            return;
        }
        if (addNewBook) {
            try {
                if (!modelBook.validDatabookID(txtBookID.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "DUPLICATED BOOKID at " + txtBookID.getText().trim());
                    return;
                }
                Books_SE140736 b = new Books_SE140736(txtBookID.getText().toUpperCase().trim(),
                        txtBookName.getText().trim(),
                        txtAuthor.getText().trim(),
                        txtPublisher.getText().trim(),
                        Integer.parseInt(cbxPublishedYear.getSelectedItem().toString()),
                        chkForRent.isSelected());
                if (modelBook.Insert(b) == SUCCESS) {
                    modelBook.getModelBooks().getList().add(b);
                }
                addNewBook = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblBook.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Please Choose Row to Edit");
                }

                Books_SE140736 bOld = modelBook.getModelBooks().getList().get(selectedRow);
                Books_SE140736 bNew = new Books_SE140736(txtBookID.getText().trim().toUpperCase(),
                        txtBookName.getText().trim(),
                        txtAuthor.getText().trim(),
                        txtPublisher.getText().trim(),
                        Integer.parseInt(cbxPublishedYear.getSelectedItem().toString()),
                        chkForRent.isSelected());
                if (modelBook.Save(bNew) == SUCCESS) {
                    bOld.setBookName(bNew.getBookName());
                    bOld.setAuthor(bNew.getAuthor());
                    bOld.setPublisher(bNew.getPublisher());
                    bOld.setPublishedYear(bNew.getPublishedYear());
                    bOld.setForRent(bNew.isForRent());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tblBook.updateUI();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        try {
            int selectedRow = tblBook.getSelectedRow();
            if (selectedRow < 0 || deleteBook == false) {
                JOptionPane.showMessageDialog(this, "Choose the Row to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Book?");
            if (r == JOptionPane.YES_OPTION) {
                Books_SE140736 b = modelBook.getModelBooks().getList().get(selectedRow);
                if (modelBook.Delete(b) == SUCCESS) {
                    deleteBook = false;
                    modelBook.getModelBooks().getList().remove(b);
                    JOptionPane.showMessageDialog(this, "Deleted");
                    clearInformationBookOnTable();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblBook.updateUI();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnFindIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindIDActionPerformed
        addNewBook = false;
        String bookID = txtBookID.getText();
        try {
            modelBook.loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(ManagementUI_SE140736.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < modelBook.getModelBooks().getList().size(); i++) {
            if (bookID.equals(modelBook.getModelBooks().getList().get(i).getBookID())) {
                clearMouseClickedBook();

                modelBook = new tblBooks_SE140736();
                tblBook.setModel(modelBook.getModelBooks());

                Books_SE140736 book = modelBook.getModelBooks().getList().get(i);
                displayDetailBook(book);
                tblBook.setRowSelectionInterval(i, i); //focus dong dc chon
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Không tìm thấy ID này!");
    }//GEN-LAST:event_btnFindIDActionPerformed

    private void btnGetAllBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllBookActionPerformed
        clearAllBook();
        try {
            modelBook = new tblBooks_SE140736();
            tblBook.setModel(modelBook.getModelBooks());
        } catch (Exception ex) {
            Logger.getLogger(ManagementUI_SE140736.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGetAllBookActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String bookName = txtSearchByName.getText();
        if (bookName.length() == 0) {
            JOptionPane.showMessageDialog(null, "Search by name phải khác rỗng!");
            return;
        }
        for (int i = 0; i < modelBook.getModelBooks().getList().size(); i++) {
            if (modelBook.getModelBooks().getList().get(i).getBookName().contains(bookName) == true) {
                try {
                    modelBook = new tblBooks_SE140736();
                    modelBook.loadTableBookSearchByName(bookName);
                    tblBook.setModel(modelBook.getModelBooks());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Không tìm thấy tên sách này!");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbxSortByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSortByNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSortByNameActionPerformed

    private void cbxSortByNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSortByNameItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cbxSortByName.getSelectedIndex() == 0) {
                clearBookSort();
                try {
                    modelBook = new tblBooks_SE140736();
                    modelBook.loadBookDescending();
                } catch (SQLException ex) {
                    Logger.getLogger(ManagementUI_SE140736.class.getName()).log(Level.SEVERE, null, ex);
                }
                tblBook.setModel(modelBook.getModelBooks());
            }
            if (cbxSortByName.getSelectedIndex() == 1) {
                clearBookSort();
                try {
                    modelBook = new tblBooks_SE140736();
                    modelBook.loadBookAscending();
                } catch (SQLException ex) {
                    Logger.getLogger(ManagementUI_SE140736.class.getName()).log(Level.SEVERE, null, ex);
                }
                tblBook.setModel(modelBook.getModelBooks());
            }
        }
    }//GEN-LAST:event_cbxSortByNameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementUI_SE140736.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementUI_SE140736().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFindID;
    private javax.swing.JButton btnGetAllBook;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxPublishedYear;
    private javax.swing.JComboBox<String> cbxSortByName;
    private javax.swing.JCheckBox chkForRent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtSearchByName;
    // End of variables declaration//GEN-END:variables
}
